# Name of the workflow as it will appear in the GitHub "Actions" tab
name: Nightly Player Data Sync

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs the job on a schedule using cron syntax
  schedule:
    # This runs at 4:00 AM UTC every day.
    # It's good to offset it from your schedule sync.
    - cron: '0 4 * * *'

# A workflow run is made up of one or more jobs
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    steps:
    # 1. Checks-out your repository
    - uses: actions/checkout@v3

    # 2. Sets up a Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Match your app's Python version

    # 3. Installs your project's dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Runs the player sync script
    - name: Run NHL Player Data Sync
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python run_sync.py
