# Name of the workflow as it will appear in the GitHub "Actions" tab
name: Nightly NHL Schedule Sync

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs the job on a schedule using cron syntax
  schedule:
    # This runs at 3:00 AM UTC every day.
    # You can adjust the time as needed.
    - cron: '0 13 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # 2. Sets up a Python environment for you to use
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Match the Python version you use

    # 3. Installs your project's dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Runs the sync script to update the schedule
    - name: Run NHL Schedule Sync
      env:
        # These are the secrets you will set up in the next part
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python scripts/sync_schedule.py